version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Test it
          command: bash test.sh
